name: Check PR title
on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request title
        uses: thehanimo/pr-title-checker@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
